- id: copy-codex-sessions
  name: Copy Codex sessions for this workspace
  description: |
    Reads ~/.codex/sessions/*.jsonl files, filters by cwd, and writes Markdown
    transcripts into codex_message/ before each commit.
  entry: scripts/copy_codex_sessions.sh
  language: script
  pass_filenames: false
  stages: [commit]
